### ISSUE TITLE
slnEnv Variable in README.MD

### ISSUE THREAD

**Issue by astrohart** [3F/MvsSln#31]
See:

![fig01](https://user-images.githubusercontent.com/8261875/90767653-8d8fe180-e2bb-11ea-9981-ddf305aa12c5.png)

What's this variable?  Where is it declared?  Kindly please add the declaration of this variable to the example code, so that I might know why it's there/how to utilize this package.

Respectfully,

Brian H

**Comment by 3F** [comment]
Hello Brian,

I am sorry for the unclear samples. I remind everyone can improve it via PR.

`slnEnv` variable in readme points to **sln**.Result.**Env** with its default implementation of the available environments.
https://github.com/3F/MvsSln/blob/9ce5885282d65ee32bfc03808c83c1113c1928e3/MvsSln/Core/IEnvironment.cs#L32

To be clear, after #17 MvsSln 2.4+ may provide a several implementations such as basic IXProjectEnv environment and IEnvironment with IDisposable pattern.

The reason of IXProjectEnv was described in #17 and in short it delegates the releasing of resources at the user's choice. When, for example, you don't need to release it at all.

This concerns to programs like [vsSolutionBuildEvent](https://github.com/3F/vsSolutionBuildEvent) that works in various environments (VS EnvDTE, MSBuild, etc), this is it:

* For EnvDTE: https://github.com/3F/vsSolutionBuildEvent/blob/014f49ad6c84caaf2448d6876afcf9f4d1a9e052/vsSolutionBuildEvent/Environment.cs#L379
* For MSBuild or like: https://github.com/3F/vsSolutionBuildEvent/blob/014f49ad6c84caaf2448d6876afcf9f4d1a9e052/vsSolutionBuildEvent/IsolatedEnv.cs#L270

For the default\* behavior MvsSln still works with IEnvironment which requires the use of disposing.

\*The default behavior means our *Sln wrapper* with related flags, for example:

```csharp
using(var sln = new Sln("...", SlnItems.Env | SlnItems.LoadMinimalDefaultData)
{
    //...
} // sln.Result.Env will be released as soon as GC will collect this outside this scope
```
Because some manual way is also provided like https://github.com/3F/DllExport/blob/master/Wizard/DxpIsolatedEnv.cs

Let me know if you still have the questions or problems.
