### ISSUE TITLE
Is there any good documentation???

### ISSUE THREAD

**Issue by DynConcepts** [3F/MvsSln#36]
Strugginly with something that should be simple (IMHO)... I have 

`  var items = mvsProj.GetItems();`

Now for each item (iteration is not the problem), how do I get to the file name???

I feel bad asking these questions as they are not "issues..... But some documentation beyond what is on the start page (or downloading an understanding the source) should be great .... hopefully I am just missing something obvious.)

(note, the best I could come up was filtering on the "type" property...

**Comment by 3F** [comment]
> Now for each item (iteration is not the problem), how do I get to the file name???

Either

https://github.com/3F/MvsSln/blob/9ce5885282d65ee32bfc03808c83c1113c1928e3/MvsSln/Projects/Item.cs#L91-L97

or use

https://github.com/3F/MvsSln/blob/9ce5885282d65ee32bfc03808c83c1113c1928e3/MvsSln/Projects/Item.cs#L43-L51


@DynConcepts

Actually MvsSln was extracted from https://github.com/3F/vsSolutionBuildEvent as independent project too late at 18 Jun 2017;
And today this is normal to ask everything related to its use together with its bugs and features. Because yes, we don't really have a good documentation yet except src and unit-tests.

I have already [voiced earlier](https://github.com/3F/MvsSln/issues/27#issuecomment-650455307) that some parts are not so good covered for most convenient use today (like IXProject, or even like #10) because it was just a quick migration from [vsSolutionBuildEvent](https://github.com/3F/vsSolutionBuildEvent).

That's why I'd love to see any help from the community at least in our wiki, and so on.

But just to be clear, [I had many tasks](https://ko-fi.com/post/Sdk-style-in-projects-and-repairing-solution-prope-O4O71YTM4) in my timeline around MvsSln and IeXod as you can see it; But unfortunately I am stuck due to my life problems and currently [it's still hard to manage time for something more](https://twitter.com/GitHub3F/status/1338116044825780228) but [I am trying it](https://twitter.com/GitHub3F/status/1320425255291265026) and of course welcome everyone who is willing to improve something here

> I feel bad asking these questions as they are not "issues.....

It should actually look like Q & A. Later, of course, this *can be* explicitly limited like [here](https://github.com/3F/DllExport/issues/new?labels=question&template=question.md). So don't worry yet.

**Comment by DynConcepts** [comment]
👍👍

**Comment by 3F** [comment]
> It should actually look like Q & A ...

almost forget about the new feature (beta as of this day) on github 

> **Discussions** is the space for your community to have conversations, ask questions and post answers without opening issues.

Never used yet and still not sure if needed for my repositories at all. Because I think this is only good for repos where high activities and you definitely need to separate users from dev members. But who knows...
