### ISSUE TITLE
Migrate to .NET Core away from .NET Framework

### ISSUE THREAD

**Issue by villelaitila** [3F/MvsSln#48]
Would make it more useful

**Comment by 3F** [comment]
MvsSln fully supports .NET Core or what do you mean?

**Comment by villelaitila** [comment]
![Screenshot from 2021-04-09 18-17-55](https://user-images.githubusercontent.com/5195944/114202605-0386ad00-9960-11eb-86b2-666b974be3bd.png)
it doesn't look promising...

**Comment by villelaitila** [comment]
Is there some way to build & run it on linux, without mono..?

**Comment by 3F** [comment]
Needs a new rules for correct targeting in linux environment since we build using windows machine https://ci.appveyor.com/project/3Fs/mvssln-fxjnf/builds/37050016

Just update this line https://github.com/3F/MvsSln/blob/9ce5885282d65ee32bfc03808c83c1113c1928e3/MvsSln/MvsSln.csproj#L10

Temporarily patch the original values as needed by overriding or splitting them using Condition xml attributes.
Use PR to commit your changes for everyone. I'll try to review this asap.

**Comment by 3F** [comment]
Today's [Conari](https://github.com/3F/Conari) was configured for related issue.

https://github.com/3F/Conari/blob/ba1a82e1a7c9250e5806b5d72444be5c3b57850c/common.props#L9-L21

Can anyone check this for MvsSln project too?
If this fits, then we can merge the changes. PR is welcomed.

**Comment by 3F** [comment]
I close this issue because of latest changes. Here's build example for linux,

Build worker image Ubuntu2004: 

> dotnet build -c PublicRelease

f10c50cc, https://ci.appveyor.com/project/3Fs/mvssln-2d2c2/builds/40491644#L1

Feel free to continue if you still have some problems.
