### ISSUE TITLE
Removal of project/solution configurations...

### ISSUE THREAD

**Issue by davidcorbin-atmosera** [3F/MvsSln#54]
Over time, project/solutions get lots of build configurations added. I have successfully iterated and found a list and now want to purge...

Going manually into Visual Studio and deleting is not an option (I am looking at nearly 10K kills!!!!)... nut I am also not seeing a way to modify the collections and re-write the respective project (including .vcxproj, and vcsproj) files...

Am I missing something? Are heir any recommendations? Do I have to start writing raw tooling?

Thanks in Advance

**Comment by 3F** [comment]
Hello David,
Did you try something like https://github.com/3F/MvsSln/discussions/42

About locked collections in sln result, see #9
But it's all about convenience and you can re-write (construct)
anything using collections at runtime through map and its writer.

Some related example can be found also here
https://github.com/3F/MvsSln/discussions/43#discussioncomment-371185

 > "Do I have to start writing raw tooling?"

Not for this, since that's a common use.
I recommend to start detailed Q&A in Discussions here to find some final 
solutions in your case.

Unfortunately I may be very slow to respond due to many reasons beyond 
my control.
But maybe someone else will be faster than me.
